<a href="https://colab.research.google.com/github/KoaMiranda/CS165P1/blob/main/Project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import fileinput as fi #unnecessary? loadtext?
import numpy as np

In [ ]:
#make big txt file 1-256
import random as rand
rand.seed()
test_txt = open("test.txt", "w")
for i in range(rand.randint(1,256)):
  test_txt.write(str(rand.random()*10) + "\t" + str(rand.random()*10) + "\n")
test_txt.close()

In [ ]:
def file_grabber():
  txt_file = input("please enter a txt_file name: ")
  locs = np.loadtxt(txt_file, dtype=np.double)
  return locs

arr = file_grabber() #debug

please enter a txt_file name: test.txt


In [ ]:
def eucl_dist(inp: np.array((),dtype=np.double)):
  ignore = 0
  rows = inp.shape[0]
  cols = inp.shape[1]
  gNNmatrix = np.zeros((rows,rows))

  for i in range(rows):
      temp = list(range(cols)) #for the x,y coords
      for j in range(rows):
          if j < ignore: continue #ex. when j == 3, should skip 0,1,2
          if i == j: continue #skip the diagonal

          for k in range(cols):
            temp[k] = inp[i,k] - inp[j,k] #ex. row 2, inp([2][0]) - inp([3+0][0])
          temp[0] = temp[0]**2 #x-coord
          temp[1] = temp[1]**2 #y-coord
          total = temp[0] + temp[1]
          ed = np.sqrt(total) #euclidean distance
          gNNmatrix[i][j] = ed # assign it to the global NxN matrix
      ignore += 1 #only top triangle of matrix
  return gNNmatrix

print(eucl_dist(arr)) #debug
# eucl_dist(arr) #debug

[[0.         2.52115002 7.30641842 ... 4.75867512 1.57182309 6.93772201]
 [0.         0.         7.92132779 ... 4.04416792 3.32922057 7.73055811]
 [0.         0.         0.         ... 4.48567518 5.77720216 0.6175444 ]
 ...
 [0.         0.         0.         ... 0.         3.89533981 4.53317062]
 [0.         0.         0.         ... 0.         0.         5.38502726]
 [0.         0.         0.         ... 0.         0.         0.        ]]


array([[0.        , 2.52115002, 7.30641842, ..., 4.75867512, 1.57182309,
        6.93772201],
       [0.        , 0.        , 7.92132779, ..., 4.04416792, 3.32922057,
        7.73055811],
       [0.        , 0.        , 0.        , ..., 4.48567518, 5.77720216,
        0.6175444 ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 3.89533981,
        4.53317062],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        5.38502726],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])